import ExcelJS from "exceljs";
import * as XLSX from "xlsx";
import { metadataSheetName, workbookSheetNames, type WorkbookMetadata } from "./index";

export interface ParsedSheet {
  name: string;
  headers: string[];
  rows: Array<Record<string, string | number | boolean | null>>;
}

export interface ParsedWorkbook {
  sheets: ParsedSheet[];
  metadata?: WorkbookMetadata;
}

type SheetRow = unknown[];

function normalizeCell(value: unknown): string | number | boolean | null {
  if (value === null || value === undefined) return null;
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") return value;
  if (value instanceof Date) return value.toISOString();
  return String(value);
}

function rowHasContent(row: SheetRow): number {
  if (!Array.isArray(row)) return 0;
  return row.filter((cell) => normalizeCell(cell) !== null && normalizeCell(cell) !== "").length;
}

function parseAoaRegion(name: string, aoa: SheetRow[], startIndex: number): ParsedSheet | undefined {
  let headerIndex = -1;
  for (let index = startIndex; index < aoa.length; index += 1) {
    if (rowHasContent(aoa[index] ?? []) >= 2) { headerIndex = index; break; }
  }
  if (headerIndex < 0) return undefined;

  const headerRow = aoa[headerIndex] ?? [];
  let lastColumn = headerRow.length;
  while (lastColumn > 0 && normalizeCell(headerRow[lastColumn - 1]) === null) lastColumn -= 1;
  const headers: string[] = [];
  for (let column = 0; column < lastColumn; column += 1) headers.push(String(normalizeCell(headerRow[column]) ?? `列${column + 1}`));

  const rows: ParsedSheet["rows"] = [];
  let emptyStreak = 0;
  for (let rowIndex = headerIndex + 1; rowIndex < aoa.length; rowIndex += 1) {
    const sourceRow = aoa[rowIndex] ?? [];
    if (rowHasContent(sourceRow) === 0) {
      emptyStreak += 1;
      if (emptyStreak >= 2) break;
      continue;
    }
    emptyStreak = 0;
    const row: Record<string, string | number | boolean | null> = {};
    headers.forEach((header, column) => { row[header] = normalizeCell(sourceRow[column]); });
    rows.push(row);
  }
  return { name, headers, rows };
}

export async function parseCompatibleWorkbook(buffer: Uint8Array): Promise<ParsedWorkbook> {
  const data = typeof Buffer !== "undefined" ? Buffer.from(buffer) : buffer;
  const workbook = XLSX.read(data, { type: "buffer", cellDates: true, dense: false });
  const parsed: ParsedWorkbook = { sheets: [] };

  const metadataSheet = workbook.Sheets[metadataSheetName];
  if (metadataSheet) {
    const cell = metadataSheet.A1;
    if (cell && typeof cell.v === "string") {
      try { parsed.metadata = JSON.parse(cell.v) as WorkbookMetadata; } catch { /* 忽略损坏的元数据 */ }
    }
  }

  for (const sheetName of workbookSheetNames) {
    const sheet = workbook.Sheets[sheetName];
    if (!sheet) continue;
    const aoa = XLSX.utils.sheet_to_json<SheetRow>(sheet, { header: 1, raw: true, defval: null, blankrows: true });
    const region = parseAoaRegion(sheetName, aoa, 2);
    if (region) parsed.sheets.push(region);
    if (sheetName === "02类型材质" && aoa.length > 8) {
      const materialRegion = parseAoaRegion("02类型材质/线材质", aoa, 8);
      if (materialRegion) parsed.sheets.push(materialRegion);
    }
  }

  // 兜底：若工作簿不含编号表（如母表 v1.0），则解析其全部表
  if (parsed.sheets.length === 0) {
    for (const sheetName of workbook.SheetNames) {
      const sheet = workbook.Sheets[sheetName];
      if (!sheet) continue;
      const aoa = XLSX.utils.sheet_to_json<SheetRow>(sheet, { header: 1, raw: true, defval: null, blankrows: true });
      const region = parseAoaRegion(sheetName, aoa, 0);
      if (region) parsed.sheets.push(region);
    }
  }

  return parsed;
}

export async function createCompatibleWorkbook(metadata: WorkbookMetadata): Promise<Uint8Array> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Tackle Forger";
  workbook.created = new Date(metadata.exportedAt);

  workbookSheetNames.forEach((name) => {
    const worksheet = workbook.addWorksheet(name);
    worksheet.getCell("A1").value = name;
    worksheet.getCell("A2").value = "Generated by Tackle Forger. Web calculations are authoritative.";
    worksheet.mergeCells("A1:H1");
    worksheet.mergeCells("A2:H2");
    worksheet.getCell("A1").font = { bold: true, size: 16, color: { argb: "FFF1F7F5" } };
    worksheet.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF102721" } };
  });

  const hidden = workbook.addWorksheet(metadataSheetName, { state: "veryHidden" });
  hidden.getCell("A1").value = JSON.stringify(metadata);

  const output = await workbook.xlsx.writeBuffer();
  return new Uint8Array(output);
}
